CREATE TABLE pokemon_products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  canonical_key TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  product_type TEXT NOT NULL,
  set_name TEXT,
  pack_count INTEGER,
  image_url TEXT,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pokemon_products_canonical_key_nonempty CHECK (BTRIM(canonical_key) <> ''),
  CONSTRAINT pokemon_products_name_nonempty CHECK (BTRIM(name) <> ''),
  CONSTRAINT pokemon_products_product_type_nonempty CHECK (BTRIM(product_type) <> ''),
  CONSTRAINT pokemon_products_pack_count_positive CHECK (pack_count IS NULL OR pack_count > 0),
  CONSTRAINT pokemon_products_metadata_object CHECK (JSONB_TYPEOF(metadata) = 'object')
);

CREATE INDEX idx_pokemon_products_active_type
  ON pokemon_products (product_type, canonical_key)
  WHERE active;

CREATE TABLE source_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_key TEXT NOT NULL UNIQUE,
  source_type TEXT NOT NULL,
  display_name TEXT NOT NULL,
  canonical_url TEXT,
  independence_group TEXT NOT NULL,
  reliability_score NUMERIC(5, 2) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT source_profiles_source_key_nonempty CHECK (BTRIM(source_key) <> ''),
  CONSTRAINT source_profiles_source_type_nonempty CHECK (BTRIM(source_type) <> ''),
  CONSTRAINT source_profiles_display_name_nonempty CHECK (BTRIM(display_name) <> ''),
  CONSTRAINT source_profiles_independence_group_nonempty CHECK (BTRIM(independence_group) <> ''),
  CONSTRAINT source_profiles_reliability_range CHECK (reliability_score BETWEEN 0 AND 100),
  CONSTRAINT source_profiles_metadata_object CHECK (JSONB_TYPEOF(metadata) = 'object')
);

CREATE INDEX idx_source_profiles_independence_reliability
  ON source_profiles (independence_group, reliability_score DESC)
  WHERE active;

CREATE INDEX idx_source_profiles_type_active
  ON source_profiles (source_type, active);

CREATE TABLE tracked_locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_key TEXT NOT NULL UNIQUE,
  country_code CHAR(2) NOT NULL,
  postal_code TEXT NOT NULL,
  label TEXT NOT NULL,
  timezone TEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tracked_locations_country_postal_unique UNIQUE (country_code, postal_code),
  CONSTRAINT tracked_locations_location_key_nonempty CHECK (BTRIM(location_key) <> ''),
  CONSTRAINT tracked_locations_country_code_uppercase CHECK (country_code = UPPER(country_code)),
  CONSTRAINT tracked_locations_postal_code_nonempty CHECK (BTRIM(postal_code) <> ''),
  CONSTRAINT tracked_locations_label_nonempty CHECK (BTRIM(label) <> ''),
  CONSTRAINT tracked_locations_timezone_nonempty CHECK (BTRIM(timezone) <> '')
);

INSERT INTO tracked_locations (
  location_key,
  country_code,
  postal_code,
  label,
  timezone
) VALUES (
  'us:29631',
  'US',
  '29631',
  'Clemson, SC 29631',
  'America/New_York'
);

CREATE TABLE release_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_key TEXT NOT NULL UNIQUE,
  pokemon_product_id BIGINT REFERENCES pokemon_products(id) ON DELETE SET NULL,
  retailer_id TEXT,
  event_type TEXT NOT NULL,
  title TEXT NOT NULL,
  status TEXT NOT NULL,
  date_precision TEXT NOT NULL,
  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ,
  confidence_score NUMERIC(5, 2) NOT NULL,
  source_url TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT release_events_event_key_nonempty CHECK (BTRIM(event_key) <> ''),
  CONSTRAINT release_events_event_type_nonempty CHECK (BTRIM(event_type) <> ''),
  CONSTRAINT release_events_title_nonempty CHECK (BTRIM(title) <> ''),
  CONSTRAINT release_events_status_nonempty CHECK (BTRIM(status) <> ''),
  CONSTRAINT release_events_date_precision_nonempty CHECK (BTRIM(date_precision) <> ''),
  CONSTRAINT release_events_confidence_range CHECK (confidence_score BETWEEN 0 AND 100),
  CONSTRAINT release_events_valid_window CHECK (ends_at IS NULL OR ends_at >= starts_at),
  CONSTRAINT release_events_metadata_object CHECK (JSONB_TYPEOF(metadata) = 'object')
);

CREATE INDEX idx_release_events_upcoming
  ON release_events (starts_at, status);

CREATE INDEX idx_release_events_product_start
  ON release_events (pokemon_product_id, starts_at);

CREATE INDEX idx_release_events_retailer_start
  ON release_events (retailer_id, starts_at);

CREATE TABLE retailer_listings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pokemon_product_id BIGINT NOT NULL REFERENCES pokemon_products(id) ON DELETE RESTRICT,
  retailer_id TEXT NOT NULL,
  retailer_sku TEXT,
  canonical_url TEXT NOT NULL,
  seller_classification TEXT NOT NULL,
  availability_state TEXT NOT NULL,
  access_state TEXT NOT NULL,
  country_code CHAR(2) NOT NULL DEFAULT 'US',
  price NUMERIC(12, 2),
  currency CHAR(3) NOT NULL DEFAULT 'USD',
  first_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_observed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_checked_at TIMESTAMPTZ,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT retailer_listings_retailer_url_unique UNIQUE (retailer_id, canonical_url),
  CONSTRAINT retailer_listings_retailer_id_nonempty CHECK (BTRIM(retailer_id) <> ''),
  CONSTRAINT retailer_listings_url_nonempty CHECK (BTRIM(canonical_url) <> ''),
  CONSTRAINT retailer_listings_seller_nonempty CHECK (BTRIM(seller_classification) <> ''),
  CONSTRAINT retailer_listings_availability_nonempty CHECK (BTRIM(availability_state) <> ''),
  CONSTRAINT retailer_listings_access_nonempty CHECK (BTRIM(access_state) <> ''),
  CONSTRAINT retailer_listings_country_code_uppercase CHECK (country_code = UPPER(country_code)),
  CONSTRAINT retailer_listings_currency_uppercase CHECK (currency = UPPER(currency)),
  CONSTRAINT retailer_listings_price_nonnegative CHECK (price IS NULL OR price >= 0),
  CONSTRAINT retailer_listings_seen_window CHECK (last_seen_at >= first_seen_at),
  CONSTRAINT retailer_listings_metadata_object CHECK (JSONB_TYPEOF(metadata) = 'object')
);

CREATE UNIQUE INDEX uq_retailer_listings_retailer_sku
  ON retailer_listings (retailer_id, retailer_sku)
  WHERE retailer_sku IS NOT NULL;

CREATE INDEX idx_retailer_listings_product
  ON retailer_listings (pokemon_product_id);

CREATE INDEX idx_retailer_listings_availability_observed
  ON retailer_listings (retailer_id, availability_state, last_observed_at DESC)
  WHERE active;

CREATE TABLE scrape_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_key TEXT NOT NULL UNIQUE,
  retailer_id TEXT NOT NULL,
  retailer_listing_id BIGINT REFERENCES retailer_listings(id) ON DELETE SET NULL,
  tracked_location_id BIGINT REFERENCES tracked_locations(id) ON DELETE SET NULL,
  run_type TEXT NOT NULL,
  status TEXT NOT NULL,
  started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMPTZ,
  http_status INTEGER,
  error_code TEXT,
  error_detail TEXT,
  observed_availability_state TEXT,
  observed_seller_classification TEXT,
  observed_price NUMERIC(12, 2),
  observed_currency CHAR(3),
  metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT scrape_runs_run_key_nonempty CHECK (BTRIM(run_key) <> ''),
  CONSTRAINT scrape_runs_retailer_id_nonempty CHECK (BTRIM(retailer_id) <> ''),
  CONSTRAINT scrape_runs_run_type_nonempty CHECK (BTRIM(run_type) <> ''),
  CONSTRAINT scrape_runs_status_nonempty CHECK (BTRIM(status) <> ''),
  CONSTRAINT scrape_runs_http_status_range CHECK (http_status IS NULL OR http_status BETWEEN 100 AND 599),
  CONSTRAINT scrape_runs_price_nonnegative CHECK (observed_price IS NULL OR observed_price >= 0),
  CONSTRAINT scrape_runs_currency_uppercase CHECK (observed_currency IS NULL OR observed_currency = UPPER(observed_currency)),
  CONSTRAINT scrape_runs_valid_window CHECK (completed_at IS NULL OR completed_at >= started_at),
  CONSTRAINT scrape_runs_metadata_object CHECK (JSONB_TYPEOF(metadata) = 'object')
);

CREATE INDEX idx_scrape_runs_listing_recent
  ON scrape_runs (retailer_listing_id, started_at DESC);

CREATE INDEX idx_scrape_runs_retailer_recent
  ON scrape_runs (retailer_id, started_at DESC);

CREATE INDEX idx_scrape_runs_status_recent
  ON scrape_runs (status, started_at DESC);

CREATE TABLE signals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ingestion_key TEXT NOT NULL UNIQUE,
  source_profile_id BIGINT NOT NULL REFERENCES source_profiles(id) ON DELETE RESTRICT,
  pokemon_product_id BIGINT REFERENCES pokemon_products(id) ON DELETE SET NULL,
  retailer_listing_id BIGINT REFERENCES retailer_listings(id) ON DELETE SET NULL,
  release_event_id BIGINT REFERENCES release_events(id) ON DELETE SET NULL,
  signal_type TEXT NOT NULL,
  subject_text TEXT NOT NULL,
  source_url TEXT,
  event_fingerprint TEXT NOT NULL,
  published_at TIMESTAMPTZ,
  observed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  confidence_score NUMERIC(5, 2) NOT NULL,
  payload JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT signals_ingestion_key_nonempty CHECK (BTRIM(ingestion_key) <> ''),
  CONSTRAINT signals_signal_type_nonempty CHECK (BTRIM(signal_type) <> ''),
  CONSTRAINT signals_subject_nonempty CHECK (BTRIM(subject_text) <> ''),
  CONSTRAINT signals_fingerprint_nonempty CHECK (BTRIM(event_fingerprint) <> ''),
  CONSTRAINT signals_confidence_range CHECK (confidence_score BETWEEN 0 AND 100),
  CONSTRAINT signals_payload_object CHECK (JSONB_TYPEOF(payload) = 'object')
);

CREATE INDEX idx_signals_fingerprint_recent
  ON signals (event_fingerprint, observed_at DESC);

CREATE INDEX idx_signals_source_recent
  ON signals (source_profile_id, observed_at DESC);

CREATE INDEX idx_signals_product_recent
  ON signals (pokemon_product_id, observed_at DESC);

CREATE INDEX idx_signals_listing_recent
  ON signals (retailer_listing_id, observed_at DESC);

CREATE TABLE readiness_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  calculation_key TEXT NOT NULL UNIQUE,
  pokemon_product_id BIGINT NOT NULL REFERENCES pokemon_products(id) ON DELETE RESTRICT,
  retailer_listing_id BIGINT REFERENCES retailer_listings(id) ON DELETE SET NULL,
  release_event_id BIGINT REFERENCES release_events(id) ON DELETE SET NULL,
  policy_version TEXT NOT NULL,
  readiness_score NUMERIC(5, 2) NOT NULL,
  readiness_band TEXT NOT NULL,
  independent_source_count INTEGER NOT NULL DEFAULT 0,
  component_scores JSONB NOT NULL DEFAULT '{}'::JSONB,
  inputs JSONB NOT NULL DEFAULT '{}'::JSONB,
  calculated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT readiness_snapshots_key_nonempty CHECK (BTRIM(calculation_key) <> ''),
  CONSTRAINT readiness_snapshots_policy_nonempty CHECK (BTRIM(policy_version) <> ''),
  CONSTRAINT readiness_snapshots_band_nonempty CHECK (BTRIM(readiness_band) <> ''),
  CONSTRAINT readiness_snapshots_score_range CHECK (readiness_score BETWEEN 0 AND 100),
  CONSTRAINT readiness_snapshots_sources_nonnegative CHECK (independent_source_count >= 0),
  CONSTRAINT readiness_snapshots_components_object CHECK (JSONB_TYPEOF(component_scores) = 'object'),
  CONSTRAINT readiness_snapshots_inputs_object CHECK (JSONB_TYPEOF(inputs) = 'object')
);

CREATE INDEX idx_readiness_snapshots_product_latest
  ON readiness_snapshots (pokemon_product_id, calculated_at DESC);

CREATE INDEX idx_readiness_snapshots_listing_latest
  ON readiness_snapshots (retailer_listing_id, calculated_at DESC);

CREATE INDEX idx_readiness_snapshots_score_latest
  ON readiness_snapshots (readiness_score DESC, calculated_at DESC);

CREATE TABLE value_scores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  calculation_key TEXT NOT NULL UNIQUE,
  pokemon_product_id BIGINT NOT NULL REFERENCES pokemon_products(id) ON DELETE RESTRICT,
  retailer_listing_id BIGINT REFERENCES retailer_listings(id) ON DELETE SET NULL,
  policy_version TEXT NOT NULL,
  rated BOOLEAN NOT NULL,
  unrated_reason TEXT,
  price NUMERIC(12, 2),
  pack_count INTEGER,
  price_per_pack NUMERIC(12, 4),
  value_score NUMERIC(5, 2),
  star_rating SMALLINT,
  value_tag TEXT,
  inputs JSONB NOT NULL DEFAULT '{}'::JSONB,
  calculated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT value_scores_key_nonempty CHECK (BTRIM(calculation_key) <> ''),
  CONSTRAINT value_scores_policy_nonempty CHECK (BTRIM(policy_version) <> ''),
  CONSTRAINT value_scores_price_nonnegative CHECK (price IS NULL OR price >= 0),
  CONSTRAINT value_scores_pack_count_positive CHECK (pack_count IS NULL OR pack_count > 0),
  CONSTRAINT value_scores_price_per_pack_nonnegative CHECK (price_per_pack IS NULL OR price_per_pack >= 0),
  CONSTRAINT value_scores_score_range CHECK (value_score IS NULL OR value_score BETWEEN 0 AND 100),
  CONSTRAINT value_scores_star_range CHECK (star_rating IS NULL OR star_rating BETWEEN 1 AND 5),
  CONSTRAINT value_scores_inputs_object CHECK (JSONB_TYPEOF(inputs) = 'object'),
  CONSTRAINT value_scores_rating_consistency CHECK (
    (
      rated
      AND unrated_reason IS NULL
      AND price IS NOT NULL
      AND pack_count IS NOT NULL
      AND price_per_pack IS NOT NULL
      AND value_score IS NOT NULL
      AND star_rating IS NOT NULL
      AND value_tag IS NOT NULL
    )
    OR
    (
      NOT rated
      AND unrated_reason IS NOT NULL
      AND value_score IS NULL
      AND star_rating IS NULL
      AND value_tag IS NULL
    )
  )
);

CREATE INDEX idx_value_scores_product_latest
  ON value_scores (pokemon_product_id, calculated_at DESC);

CREATE INDEX idx_value_scores_listing_latest
  ON value_scores (retailer_listing_id, calculated_at DESC);

CREATE INDEX idx_value_scores_rated_score_latest
  ON value_scores (value_score DESC, calculated_at DESC)
  WHERE rated;

CREATE TABLE opportunities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  opportunity_key TEXT NOT NULL UNIQUE,
  pokemon_product_id BIGINT NOT NULL REFERENCES pokemon_products(id) ON DELETE RESTRICT,
  retailer_listing_id BIGINT REFERENCES retailer_listings(id) ON DELETE SET NULL,
  release_event_id BIGINT REFERENCES release_events(id) ON DELETE SET NULL,
  readiness_snapshot_id BIGINT REFERENCES readiness_snapshots(id) ON DELETE SET NULL,
  value_score_id BIGINT REFERENCES value_scores(id) ON DELETE SET NULL,
  policy_version TEXT NOT NULL,
  tier TEXT NOT NULL,
  availability_state TEXT NOT NULL,
  seller_classification TEXT NOT NULL,
  eligible BOOLEAN NOT NULL,
  independent_source_count INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL,
  first_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT opportunities_key_nonempty CHECK (BTRIM(opportunity_key) <> ''),
  CONSTRAINT opportunities_policy_nonempty CHECK (BTRIM(policy_version) <> ''),
  CONSTRAINT opportunities_tier_nonempty CHECK (BTRIM(tier) <> ''),
  CONSTRAINT opportunities_availability_nonempty CHECK (BTRIM(availability_state) <> ''),
  CONSTRAINT opportunities_seller_nonempty CHECK (BTRIM(seller_classification) <> ''),
  CONSTRAINT opportunities_status_nonempty CHECK (BTRIM(status) <> ''),
  CONSTRAINT opportunities_sources_nonnegative CHECK (independent_source_count >= 0),
  CONSTRAINT opportunities_seen_window CHECK (last_seen_at >= first_seen_at),
  CONSTRAINT opportunities_expiry_window CHECK (expires_at IS NULL OR expires_at >= first_seen_at)
);

CREATE INDEX idx_opportunities_active_priority
  ON opportunities (tier, last_seen_at DESC)
  WHERE status = 'active';

CREATE INDEX idx_opportunities_product
  ON opportunities (pokemon_product_id);

CREATE INDEX idx_opportunities_listing
  ON opportunities (retailer_listing_id);
